// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class FileView {
    "Index": number;
    "Name": string;
    "Size": number;
    "Completed": number;
    "Priority": number;

    /** Creates a new FileView instance. */
    constructor($$source: Partial<FileView> = {}) {
        if (!("Index" in $$source)) {
            this["Index"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Size" in $$source)) {
            this["Size"] = 0;
        }
        if (!("Completed" in $$source)) {
            this["Completed"] = 0;
        }
        if (!("Priority" in $$source)) {
            this["Priority"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileView instance from a string or object.
     */
    static createFrom($$source: any = {}): FileView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileView($$parsedSource as Partial<FileView>);
    }
}

export class PeerView {
    "Address": string;
    "Client": string;
    "Progress": number;
    "DownloadRate": number;
    "UploadRate": number;

    /** Creates a new PeerView instance. */
    constructor($$source: Partial<PeerView> = {}) {
        if (!("Address" in $$source)) {
            this["Address"] = "";
        }
        if (!("Client" in $$source)) {
            this["Client"] = "";
        }
        if (!("Progress" in $$source)) {
            this["Progress"] = 0;
        }
        if (!("DownloadRate" in $$source)) {
            this["DownloadRate"] = 0;
        }
        if (!("UploadRate" in $$source)) {
            this["UploadRate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PeerView instance from a string or object.
     */
    static createFrom($$source: any = {}): PeerView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PeerView($$parsedSource as Partial<PeerView>);
    }
}

export class Settings {
    "Autostart": boolean;
    "DownloadDir": string;
    "DownloadKiB": number;
    "UploadKiB": number;
    "MaxActive": number;
    "Seed": boolean;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("Autostart" in $$source)) {
            this["Autostart"] = false;
        }
        if (!("DownloadDir" in $$source)) {
            this["DownloadDir"] = "";
        }
        if (!("DownloadKiB" in $$source)) {
            this["DownloadKiB"] = 0;
        }
        if (!("UploadKiB" in $$source)) {
            this["UploadKiB"] = 0;
        }
        if (!("MaxActive" in $$source)) {
            this["MaxActive"] = 0;
        }
        if (!("Seed" in $$source)) {
            this["Seed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

export class Snapshot {
    "Torrents": TorrentView[];
    "Settings": Settings;
    "Events": string[];
    "Error": string;
    "DHTNodes": number;
    "Port": number;
    "Encryption": boolean;

    /** Creates a new Snapshot instance. */
    constructor($$source: Partial<Snapshot> = {}) {
        if (!("Torrents" in $$source)) {
            this["Torrents"] = [];
        }
        if (!("Settings" in $$source)) {
            this["Settings"] = (new Settings());
        }
        if (!("Events" in $$source)) {
            this["Events"] = [];
        }
        if (!("Error" in $$source)) {
            this["Error"] = "";
        }
        if (!("DHTNodes" in $$source)) {
            this["DHTNodes"] = 0;
        }
        if (!("Port" in $$source)) {
            this["Port"] = 0;
        }
        if (!("Encryption" in $$source)) {
            this["Encryption"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): Snapshot {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Torrents" in $$parsedSource) {
            $$parsedSource["Torrents"] = $$createField0_0($$parsedSource["Torrents"]);
        }
        if ("Settings" in $$parsedSource) {
            $$parsedSource["Settings"] = $$createField1_0($$parsedSource["Settings"]);
        }
        if ("Events" in $$parsedSource) {
            $$parsedSource["Events"] = $$createField2_0($$parsedSource["Events"]);
        }
        return new Snapshot($$parsedSource as Partial<Snapshot>);
    }
}

export class TorrentPreview {
    "Name": string;
    "Directory": string;

    /** Creates a new TorrentPreview instance. */
    constructor($$source: Partial<TorrentPreview> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Directory" in $$source)) {
            this["Directory"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TorrentPreview instance from a string or object.
     */
    static createFrom($$source: any = {}): TorrentPreview {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TorrentPreview($$parsedSource as Partial<TorrentPreview>);
    }
}

export class TorrentView {
    "ID": string;
    "Name": string;
    "Status": string;
    "Error": string;
    "Dir": string;
    "Added": number;
    "Size": number;
    "Completed": number;
    "Wanted": number;
    "WantedCompleted": number;
    "DownloadRate": number;
    "UploadRate": number;
    "Uploaded": number;
    "Downloaded": number;
    "Peers": number;
    "Seeds": number;
    "Ratio": number;
    "ETA": number;
    "Version": string;
    "Files": FileView[];
    "Trackers": string[];
    "History": number[];
    "BadPieces": number;
    "Hash": string;
    "Pieces": number;
    "PieceLength": number;
    "PeerList": PeerView[];

    /** Creates a new TorrentView instance. */
    constructor($$source: Partial<TorrentView> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Status" in $$source)) {
            this["Status"] = "";
        }
        if (!("Error" in $$source)) {
            this["Error"] = "";
        }
        if (!("Dir" in $$source)) {
            this["Dir"] = "";
        }
        if (!("Added" in $$source)) {
            this["Added"] = 0;
        }
        if (!("Size" in $$source)) {
            this["Size"] = 0;
        }
        if (!("Completed" in $$source)) {
            this["Completed"] = 0;
        }
        if (!("Wanted" in $$source)) {
            this["Wanted"] = 0;
        }
        if (!("WantedCompleted" in $$source)) {
            this["WantedCompleted"] = 0;
        }
        if (!("DownloadRate" in $$source)) {
            this["DownloadRate"] = 0;
        }
        if (!("UploadRate" in $$source)) {
            this["UploadRate"] = 0;
        }
        if (!("Uploaded" in $$source)) {
            this["Uploaded"] = 0;
        }
        if (!("Downloaded" in $$source)) {
            this["Downloaded"] = 0;
        }
        if (!("Peers" in $$source)) {
            this["Peers"] = 0;
        }
        if (!("Seeds" in $$source)) {
            this["Seeds"] = 0;
        }
        if (!("Ratio" in $$source)) {
            this["Ratio"] = 0;
        }
        if (!("ETA" in $$source)) {
            this["ETA"] = 0;
        }
        if (!("Version" in $$source)) {
            this["Version"] = "";
        }
        if (!("Files" in $$source)) {
            this["Files"] = [];
        }
        if (!("Trackers" in $$source)) {
            this["Trackers"] = [];
        }
        if (!("History" in $$source)) {
            this["History"] = [];
        }
        if (!("BadPieces" in $$source)) {
            this["BadPieces"] = 0;
        }
        if (!("Hash" in $$source)) {
            this["Hash"] = "";
        }
        if (!("Pieces" in $$source)) {
            this["Pieces"] = 0;
        }
        if (!("PieceLength" in $$source)) {
            this["PieceLength"] = 0;
        }
        if (!("PeerList" in $$source)) {
            this["PeerList"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TorrentView instance from a string or object.
     */
    static createFrom($$source: any = {}): TorrentView {
        const $$createField19_0 = $$createType5;
        const $$createField20_0 = $$createType3;
        const $$createField21_0 = $$createType6;
        const $$createField26_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Files" in $$parsedSource) {
            $$parsedSource["Files"] = $$createField19_0($$parsedSource["Files"]);
        }
        if ("Trackers" in $$parsedSource) {
            $$parsedSource["Trackers"] = $$createField20_0($$parsedSource["Trackers"]);
        }
        if ("History" in $$parsedSource) {
            $$parsedSource["History"] = $$createField21_0($$parsedSource["History"]);
        }
        if ("PeerList" in $$parsedSource) {
            $$parsedSource["PeerList"] = $$createField26_0($$parsedSource["PeerList"]);
        }
        return new TorrentView($$parsedSource as Partial<TorrentView>);
    }
}

// Private type creation functions
const $$createType0 = TorrentView.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Settings.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = FileView.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = PeerView.createFrom;
const $$createType8 = $Create.Array($$createType7);
