// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Add(source: string, dir: string, paused: boolean): $CancellablePromise<string> {
    return $Call.ByID(1964137038, source, dir, paused);
}

export function CreateTorrent(source: string, trackers: string): $CancellablePromise<string> {
    return $Call.ByID(3382582183, source, trackers);
}

export function OpenFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(2246272819, id);
}

export function Pause(id: string, paused: boolean): $CancellablePromise<void> {
    return $Call.ByID(2228339123, id, paused);
}

export function PickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2414355765);
}

export function PickTorrent(): $CancellablePromise<string> {
    return $Call.ByID(1375603952);
}

export function Preview(source: string): $CancellablePromise<$models.TorrentPreview> {
    return $Call.ByID(950458349, source).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Remove(id: string, deleteData: boolean): $CancellablePromise<void> {
    return $Call.ByID(3077403175, id, deleteData);
}

export function SaveSettings(settings: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(198498755, settings);
}

export function SetPriority(id: string, index: number, priority: number): $CancellablePromise<void> {
    return $Call.ByID(1026766797, id, index, priority);
}

export function Snapshot(): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(4175090251).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Verify(id: string): $CancellablePromise<void> {
    return $Call.ByID(825521734, id);
}

// Private type creation functions
const $$createType0 = $models.TorrentPreview.createFrom;
const $$createType1 = $models.Snapshot.createFrom;
